# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
    modLoader="javafml"
    # A version range to match for said mod loader - for regular FML @Mod it will be the forge version
    # Forge for 1.15.2 is version 31
    loaderVersion="[35,)"
    license="GNU GPLv3"
    # A URL to refer people to when problems occur with this mod
    issueTrackerURL="https://github.com/ghana7/ExtraCoals/issues"
    # If the mods defined in this file should show as seperate resource packs
    showAsResourcePack=false

    [[mods]]
      modId="perpetualstew"
      version="1.0"
      displayName="Perpetual Stew"
      displayURL="https://github.com/ghana7/ExtraCoals"
      logoFile="logo.png"
      credits=""
      authors="ghana7"
      description='''
      Adds the perpetual stew, a great food option for communities
      '''

      [[dependencies.perpetualstew]]
        modId="forge"
        mandatory=true
        versionRange="[35,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.perpetualstew]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.4]"
        ordering="NONE"
        side="BOTH"